name: Build, Test, and Push Docker Image

on:
  push:
    branches: [ main ]  # Trigger workflow only when main branch is updated

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Python dependencies
      run: |
        pip install --no-cache-dir pandas numpy scikit-learn matplotlib seaborn joblib

    - name: Run Python script (main.py)
      run: python main.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wine-ml-app .

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/wine-ml-app
